<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Serilog.AspNetCore" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'net7.0'">
        <PackageReference Update="Serilog.AspNetCore" VersionOverride="7.0.0" />
    </ItemGroup>
</Project>
